
##########################单机版Eureka Server的配置##############################
server:
  port: 8888

# eureka
eureka:
  instance:
    hostname: localhost
  client:
    #表示是否将自己注册到Eureka Server,默认为true
    register-with-eureka: false
    # 表示是否从Eureka Server中获取注册信息，默认为true
    fetch-registry: false
    service-url:
      #与Eureka Server交互的地址，多个地址使用，分隔
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


##########################单机版Eureka Server的配置##############################




##########################集群版Eureka Server的配置##############################
#spring:
#  profiles:
#    active: eruekaOne
#
#---
## Eureka Server One 的配置
#server:
#  port: 8888
#
#spring:
#  profiles: eurekaOne
#  application:
#    name: eurekaOne-server
#eureka:
#  instance:
#    hostname: eurekaOne
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone : http://eurekaOne:8888/eureka/,http://eurekaTwo:8889/eureka/,http://eurekaThree:8890/eureka/
#
#
#---
## Eureka Server Two 的配置
#server:
#  port: 8889
#
#spring:
#  profiles: eurekaTwo
#  application:
#    name: eurekaTwo-server
#eureka:
#  instance:
#    hostname: eurekaTwo
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone : http://eurekaOne:8888/eureka/,http://eurekaTwo:8889/eureka/,http://eurekaThree:8890/eureka/
#
#---
## Eureka Server Three 的配置
#server:
#  port: 8890
#
#spring:
#  profiles: eurekaThree
#  application:
#    name: eurekaThree-server
#eureka:
#  instance:
#    hostname: eurekaThree
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone : http://eurekaOne:8888/eureka/,http://eurekaTwo:8889/eureka/,http://eurekaThree:8890/eureka/













